[theme]
primaryColor="#007ACC"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#262730"
font="sans serif"

[server]
headless = true
enableCORS = false

[client]
showSidebarNavigation = false

[general]
pageTitle = "Mappa Servizio urbano di Jesi"
favicon = "https://raw.githubusercontent.com/Saolino91/Area_test/main/favicon-32x32.png"
